[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "aafact"
version = "0.0.1"
description = "Python wrapper for the AAFACT compiled application"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
